// Vue/src/DataCell.vue
<template>
  <div
    :class="markWeekEnd(cellData)"
  >
    <div :class="markTraining(cellData)">
      {{ cellData.text }}
    </div>
  </div>
</template>
<script lang='ts'>
export default {
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    markWeekEnd(cellData: any): Record<string, boolean> {
      function isWeekEnd(date: Date) {
        const day = date.getDay();
        return day === 0 || day === 6;
      }
      return {
        [`employee-${cellData.groups.employeeID}`]: true,
        [`employee-weekend-${cellData.groups.employeeID}`]: isWeekEnd(cellData.startDate),
      };
    },

    markTraining(cellData: any): Record<string, boolean> {
      const classObject = {
        'day-cell': true,
      } as Record<string, boolean>;

      classObject[
        this.getCurrentTraining(cellData.startDate.getDate(), cellData.groups.employeeID)
      ] = true;
      return classObject;
    },

    getCurrentTraining(date: number, employeeID: number) {
      const result = (date + employeeID) % 3;
      const currentTraining = `training-background-${result}`;

      return currentTraining;
    },
  },
};
</script>
  <style>
  .day-cell {
    height: 100%;
    background-position: center center;
    background-repeat: no-repeat;
  }

  .employee-1 {
    background-color: rgba(86, 202, 133, 0.1);
  }

  .employee-2 {
    background-color: rgba(255, 151, 71, 0.1);
  }

  .employee-weekend-1 {
    background-color: rgba(86, 202, 133, 0.2);
  }

  .employee-weekend-2 {
    background-color: rgba(255, 151, 71, 0.2);
  }

  .training-background-0 {
  background-image: url('@/assets/images/icon-abs.png');
  }

  .training-background-1 {
    background-image: url('@/assets/images/icon-step.png');
  }

  .training-background-2 {
    background-image: url('@/assets/images/icon-fitball.png');
  }

  .dx-theme-material .name h2 {
    font-size: 28px;
  }
  </style>

// React/src/DataCell.tsx
import React from 'react';

function ResourceCell(props: any): JSX.Element {
  function isWeekEnd(date: Date): boolean {
    const day = date.getDay();
    return day === 0 || day === 6;
  }

  function getCurrentTraining(date: number, employeeID: number): string {
    const result = (date + employeeID) % 3;
    const currentTraining = `training-background-${result}`;

    return currentTraining;
  }

  const { data: { startDate, groups: { employeeID }, text } } = props;
  const dayClasses = [
    'day-cell',
    getCurrentTraining(startDate.getDate(), employeeID),
  ];

  const employeeClasses = [`employee-${employeeID}`, 'dx-template-wrapper'];
  if (isWeekEnd(startDate)) {
    employeeClasses.push(`employee-weekend-${employeeID}`);
  }

  return (
    <div className={employeeClasses.join(' ')}>
      <div className={dayClasses.join(' ')}>
        {text}
      </div>
    </div>
  );
}

export default ResourceCell;
