// Angular/src/app/tooltip/tooltip.component.ts
import {
  Component, Input, Output, EventEmitter,
} from '@angular/core';
import { ClickEvent } from 'devextreme/ui/button';
import { Appointment } from 'devextreme/ui/scheduler';

@Component({
  selector: 'Tooltip',
  templateUrl: './tooltip.component.html',
})
export class TooltipComponent {
  @Input() appointmentData!: Appointment;

  @Input() markerColor!: string;

  @Input() isDeleteButtonExist!: boolean;

  @Output() onDeleteButtonClick = new EventEmitter<ClickEvent>();
}

<div class="dx-tooltip-appointment-item">
  <div class="dx-tooltip-appointment-item-marker">
    <div
      class="dx-tooltip-appointment-item-marker-body"
      [style.background-color]="markerColor"
    ></div>
  </div>

  <div class="dx-tooltip-appointment-item-content">
    <div class="dx-tooltip-appointment-item-content">
      <div class="dx-tooltip-appointment-item-content-subject">
        {{ appointmentData.text }}
      </div>
      <div class="dx-tooltip-appointment-item-content-date">
        {{ appointmentData.startDate }}
      </div>
    </div>
  </div>
  <div
    *ngIf="isDeleteButtonExist"
    class="dx-tooltip-appointment-item-delete-button-container"
  >
    <dx-button
      class="dx-tooltip-appointment-item-delete-button"
      icon="trash"
      stylingMode="text"
      (onClick)="onDeleteButtonClick.emit($event)"
    ></dx-button>
  </div>
</div>

// React/src/Tooltip.tsx
import { ClickEvent } from 'devextreme/ui/button';
import { Button } from 'devextreme-react';
import React, { useCallback } from 'react';

function Tooltip(props: any): JSX.Element {
  const onDeleteButtonClick = useCallback((e: ClickEvent) => {
    props.onDeleteButtonClick(e);
  }, []);

  return (
    <div className="dx-tooltip-appointment-item">
      <div className="dx-tooltip-appointment-item-marker">
        <div
          className="dx-tooltip-appointment-item-marker-body"
          style={{
            backgroundColor: props.color,
          }}
        ></div>
      </div>
      <div className="dx-tooltip-appointment-item-content">
        <div className="dx-tooltip-appointment-item-content">
          <div className="dx-tooltip-appointment-item-content-subject">
            {props.appointmentData.text}
          </div>
          <div className="dx-tooltip-appointment-item-content-date">
            {props.appointmentData.startDate.toString()}
          </div>
        </div>
      </div>
      {props.isDeleteButtonExist ? (
        <div className="dx-tooltip-appointment-item-delete-button-container">
          <Button
            className="dx-tooltip-appointment-item-delete-button"
            icon="trash"
            stylingMode="text"
            onClick={onDeleteButtonClick}
          ></Button>
        </div>
      ) : (
        <React.Fragment />
      )}
    </div>
  );
}

export default Tooltip;
