// React/src/App.tsx
import React, { useRef, useCallback } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';

import Scheduler, { Resource } from 'devextreme-react/scheduler';
import { ClickEvent } from 'devextreme/ui/button';
import { AppointmentTooltipTemplateData } from 'devextreme/ui/scheduler';

import { employees, data, Employee } from './data';
import DataCell from './DataCell';
import ResourceCell from './ResourceCell';
import Tooltip from './Tooltip';

const currentDate = new Date(2021, 5, 2, 11, 30);
const groups = ['employeeID'];
const views = ['month'] as any;

function App(): JSX.Element {
  const schedulerRef = useRef(null);

  const appointmentTooltip = useCallback((props: AppointmentTooltipTemplateData): JSX.Element => {
    const scheduler = schedulerRef.current as any;
    const onDeleteButtonClick = useCallback((e: ClickEvent): void => {
      scheduler.instance.deleteAppointment(props.appointmentData);
      e.event?.stopPropagation();
      scheduler.instance.hideAppointmentTooltip();
    }, []);

    function getDisabled(employeeID: number): boolean | undefined {
      return employees.find((employee: Employee) => employee.id === employeeID)?.disabled;
    }

    function getColor(employeeID: number): string | undefined {
      return employees.find((employee: Employee) => employee.id === employeeID)?.color;
    }

    const color = getColor(props.appointmentData.employeeID);

    const isDeleteButtonExist = !getDisabled(props.appointmentData.employeeID) && ((scheduler.instance.option('editing') && scheduler.instance.option('editing.allowDeleting') === true) || scheduler.instance.option('editing') === true);

    return (
      <Tooltip
        {...props}
        isDeleteButtonExist={isDeleteButtonExist}
        onDeleteButtonClick={onDeleteButtonClick}
        color={color}
      />
    );
  }, []);

  return (
    <Scheduler
      ref={schedulerRef}
      timeZone='America/Los_Angeles'
      dataSource={data}
      dataCellComponent={DataCell}
      resourceCellComponent={ResourceCell}
      groups={groups}
      views={views}
      defaultCurrentView='month'
      defaultCurrentDate={currentDate}
      height={600}
      showAllDayPanel={true}
      firstDayOfWeek={1}
      startDayHour={8}
      endDayHour={18}
      appointmentTooltipRender={appointmentTooltip}
    >
      <Resource
        label='Employee'
        fieldExpr='employeeID'
        dataSource={employees}
        allowMultiple={false}
      />
    </Scheduler>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { DxSchedulerComponent } from 'devextreme-angular';
import DataSource from 'devextreme/data/data_source';

import { ClickEvent } from 'devextreme/ui/button';
import { Appointment } from 'devextreme/ui/scheduler';
import { Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service],
})
export class AppComponent {
  @ViewChild('targetScheduler', { static: true })
    scheduler!: DxSchedulerComponent;

  dataSource = new DataSource({
    store: this.service.getData(),
  });

  currentDate: Date = new Date(2021, 5, 2, 11, 30);

  resourcesDataSource = this.service.getEmployees();

  constructor(private readonly service: Service) {
  }

  onDeleteButtonClick = (e: ClickEvent, appointmentData: Appointment): void => {
    const schedulerInstance = this.scheduler.instance;
    schedulerInstance.deleteAppointment(appointmentData);
    e.event?.stopPropagation();
    schedulerInstance.hideAppointmentTooltip();
  };

  isDeleteButtonExist = ({ appointmentData }: { appointmentData: Appointment }): boolean => {
    const schedulerInstance = this.scheduler.instance;
    const isAppointmentDisabled = appointmentData.disabled;
    const isDeleteAllowed = (schedulerInstance.option('editing') && schedulerInstance.option('editing.allowDeleting') === true)
          || schedulerInstance.option('editing') === true;

    return !isAppointmentDisabled && isDeleteAllowed;
  };

  markWeekEnd = (cellData: any): Record<string, boolean> => ({
    [`employee-${cellData.groups.employeeID}`]: true,
    [`employee-weekend-${cellData.groups.employeeID}`]: this.isWeekEnd(cellData.startDate),
  });

  markTraining = (cellData: any): Record<string, boolean> => {
    const classObject = {
      'day-cell': true,
    } as Record<string, boolean>;

    classObject[this.getCurrentTrainingClass(cellData.startDate.getDate(), cellData.groups.employeeID)] = true;
    return classObject;
  };

  getColor = (id: number): string | undefined => this.resourcesDataSource.find((employee) => employee.id === id)?.color;

  private readonly getCurrentTrainingClass = (date: number, employeeID: number): string => {
    const result = (date + employeeID) % 3;
    return `training-background-${result}`;
  };

  private readonly isWeekEnd = (date: Date): boolean => {
    const day = date.getDay();
    return day === 0 || day === 6;
  };
}

<dx-scheduler
  #targetScheduler
  timeZone="America/Los_Angeles"
  [dataSource]="dataSource"
  [views]="['month']"
  currentView="month"
  [currentDate]="currentDate"
  [firstDayOfWeek]="1"
  [startDayHour]="8"
  [endDayHour]="18"
  [showAllDayPanel]="false"
  [height]="600"
  [groups]="['employeeID']"
  resourceCellTemplate="resourceCellTemplate"
  dataCellTemplate="dataCellTemplate"
  appointmentTooltipTemplate="appointmentTooltipTemplate"
>
  <dxi-scheduler-resource
    fieldExpr="employeeID"
    [allowMultiple]="false"
    [dataSource]="resourcesDataSource"
    label="Employee"
  >
  </dxi-scheduler-resource>

  <ng-container *dxTemplate="let data of 'appointmentTooltipTemplate'">
    <!-- NOTE: You can use data.appointmentData.resouceId to obtain resource color -->
    <Tooltip
      [appointmentData]="data.appointmentData"
      [isDeleteButtonExist]="isDeleteButtonExist(data)"
      [markerColor]="getColor | apply : data.appointmentData.employeeID"
      (onDeleteButtonClick)="onDeleteButtonClick($event, data.appointmentData)"
    ></Tooltip>
  </ng-container>

  <div *dxTemplate="let employee of 'resourceCellTemplate'">
    <div class="name" [style.background]="employee.color">
      <h2>{{ employee.text }}</h2>
    </div>
    <div class="avatar">
      <img [src]="employee.data.avatar" />
    </div>
    <div class="info" [style.color]="employee.color">
      <div>Age: {{ employee.data.age }}</div>
      <div>
        <b>{{ employee.data.discipline }}</b>
      </div>
    </div>
  </div>

  <div
    *dxTemplate="let cellData of 'dataCellTemplate'"
    class="employee-weekend"
    [ngClass]="markWeekEnd | apply : cellData"
  >
    <div class="day-cell" [ngClass]="markTraining | apply : cellData">
      {{ cellData.text }}
    </div>
  </div>
</dx-scheduler>
